---
# Source: regnerdetnu/templates/deployment.web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prd-regnerdetnu-web-deployment
  namespace: regnerdetnuprd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-regnerdetnu-web-app
      version: v1
  template:
    metadata:
      labels:
        app: prd-regnerdetnu-web-app
        version: v1
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      serviceAccountName: regnerdetnu-web-sa
      imagePullSecrets:
      - name: acr-pull
      containers:
      - name: regnerdetnu-web-pod
        image: tgclzdevacr.azurecr.io/tgc-regnerdetnu-app:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: https://api.regnerdet.nu
        - name: ENVIRONMENT_TYPE
          value: prd
