---
# Source: regnerdetnu/templates/serviceaccount.web.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: regnerdetnu-web-sa
  namespace: regnerdetnuprd
  labels:
    environment: prd
    version: 1.0.15
