apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.web.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.env }}
    version: {{ .Values.api.image.tag }}
