apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.api.appName }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.env }}-{{ .Values.api.appName }}-app
  ports:
  - protocol: TCP
    port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.port }}
