apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.web.appName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.env }}
    version: {{ .Values.api.image.tag }}
spec:
  selector:
    app: {{ .Values.env }}-{{ .Values.web.appName }}-app
  ports:
  - protocol: TCP
    port: {{ .Values.web.service.port }}
    targetPort: {{ .Values.web.service.port }}
