---
# Source: regnerdetnu/templates/deployment.api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-regnerdetnu-api-deployment
  namespace: regnerdetnudev
  labels:
    environment: dev
    version: 1.0.15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-regnerdetnu-api-app
      version: 1.0.15
  template:
    metadata:
      labels:
        app: dev-regnerdetnu-api-app
        version: 1.0.15
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      serviceAccountName: regnerdetnu-api-sa
      imagePullSecrets:
      - name: acr-pull
      containers:
      - name: regnerdetnu-api-pod
        image: tgclzdevacr.azurecr.io/tgc-regnerdetnu-api:1.0.15
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: CorsAllowedOrigins
          value: https://dev.regnerdet.nu
        - name: OPEN_WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: open-weather-api-secret
              key: open-weather-api-key
