---
# Source: regnerdetnu/templates/serviceaccount.api.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: regnerdetnu-api-sa
  namespace: regnerdetnudev
  labels:
    environment: dev
    version: 1.0.19.feature-testing-stuff
