---
# Source: regnerdetnu/templates/serviceaccount.web.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: regnerdetnu-web-sa
  namespace: regnerdetnudev
  labels:
    environment: dev
    version: 1.0.11
