/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithLongitudeItemRequestBuilder, WithLongitudeItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/weather/current
 */
export interface CurrentRequestBuilder extends BaseRequestBuilder<CurrentRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.weather.current.item collection
     * @param longitude Unique identifier of the item
     * @returns {WithLongitudeItemRequestBuilder}
     */
     byLongitude(longitude: string) : WithLongitudeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CurrentRequestBuilderUriTemplate = "{+baseurl}/api/weather/current";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CurrentRequestBuilderNavigationMetadata: Record<Exclude<keyof CurrentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLongitude: {
        navigationMetadata: WithLongitudeItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["longitude"],
    },
};
/* tslint:enable */
/* eslint-enable */
