/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetCurrentWeatherQueryResponse}
 */
// @ts-ignore
export function createGetCurrentWeatherQueryResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetCurrentWeatherQueryResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * The deserialization information for the current model
 * @param GetCurrentWeatherQueryResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetCurrentWeatherQueryResponse(getCurrentWeatherQueryResponse: Partial<GetCurrentWeatherQueryResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "area": n => { getCurrentWeatherQueryResponse.area = n.getStringValue(); },
        "doesItRain": n => { getCurrentWeatherQueryResponse.doesItRain = n.getBooleanValue(); },
        "weatherDescription": n => { getCurrentWeatherQueryResponse.weatherDescription = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
export interface GetCurrentWeatherQueryResponse extends AdditionalDataHolder, Parsable {
    /**
     * The area property
     */
    area?: string | null;
    /**
     * The doesItRain property
     */
    doesItRain?: boolean | null;
    /**
     * The weatherDescription property
     */
    weatherDescription?: string | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: UntypedNode | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * Serializes information the current object
 * @param GetCurrentWeatherQueryResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetCurrentWeatherQueryResponse(writer: SerializationWriter, getCurrentWeatherQueryResponse: Partial<GetCurrentWeatherQueryResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getCurrentWeatherQueryResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("area", getCurrentWeatherQueryResponse.area);
    writer.writeBooleanValue("doesItRain", getCurrentWeatherQueryResponse.doesItRain);
    writer.writeStringValue("weatherDescription", getCurrentWeatherQueryResponse.weatherDescription);
    writer.writeAdditionalData(getCurrentWeatherQueryResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeObjectValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/* tslint:enable */
/* eslint-enable */
