/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CurrentRequestBuilderNavigationMetadata, type CurrentRequestBuilder } from './current/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/weather
 */
export interface WeatherRequestBuilder extends BaseRequestBuilder<WeatherRequestBuilder> {
    /**
     * The current property
     */
    get current(): CurrentRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WeatherRequestBuilderUriTemplate = "{+baseurl}/api/weather";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WeatherRequestBuilderNavigationMetadata: Record<Exclude<keyof WeatherRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    current: {
        navigationMetadata: CurrentRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
