/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithLatitudeItemRequestBuilder, WithLatitudeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/weather/current/{longitude}
 */
export interface WithLongitudeItemRequestBuilder extends BaseRequestBuilder<WithLongitudeItemRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.weather.current.item.item collection
     * @param latitude Unique identifier of the item
     * @returns {WithLatitudeItemRequestBuilder}
     */
     byLatitude(latitude: string) : WithLatitudeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithLongitudeItemRequestBuilderUriTemplate = "{+baseurl}/api/weather/current/{longitude}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithLongitudeItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithLongitudeItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLatitude: {
        requestsMetadata: WithLatitudeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["latitude"],
    },
};
/* tslint:enable */
/* eslint-enable */
