name: Build images
concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches: ["main"]
    paths:
    - 'src/**'
    - '.github/workflows/build_image.yml'
    - 'helm/**'
  pull_request:
    branches: ["main"]
    paths:
    - 'src/**'
    - '.github/workflows/build_image.yml'
    - 'helm/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  tag_commit:
    runs-on: ubuntu-latest
    name: Tag commit
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Generate version
      id: version
      shell: pwsh
      run: ./.github/scripts/generate_version.ps1
    
  build_web_app_arm_job:
    needs: [tag_commit]
    runs-on: ubuntu-24.04-arm
    name: Build Web App and deploy to ACR
    environment: dev
    env:
      image_name: tgc-regnerdetnu-app
      app_path: src/webapp
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v6

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.REGNERDETNU_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.REGNERDETNU_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.REGNERDETNU_DEV_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name tgclzdevacr.azurecr.io

    - name: Build and publish webapp to ACR
      run: |
        docker buildx build . \
          --platform linux/arm64 \
          --tag $acr_registry/$image_name:${{ needs.tag_commit.outputs.version }} \
          --tag $acr_registry/$image_name:latest \
          --push
      working-directory: ${{ env.app_path }}
  
  build_web_app_amd_job:
    needs: [tag_commit]
    runs-on: ubuntu-latest
    name: Build Web App and deploy to ACR
    environment: dev
    env:
      image_name: tgc-regnerdetnu-app
      app_path: src/webapp
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v6

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.REGNERDETNU_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.REGNERDETNU_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.REGNERDETNU_DEV_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name tgclzdevacr.azurecr.io

    - name: Build and publish webapp to ACR
      run: |
        docker buildx build . \
          --platform linux/amd64 \
          --tag $acr_registry/$image_name:${{ needs.tag_commit.outputs.version }} \
          --tag $acr_registry/$image_name:latest \
          --push
      working-directory: ${{ env.app_path }}

  build_web_api_arm_job:
    needs: [tag_commit]
    runs-on: ubuntu-24.04-arm
    name: Build Web API and deploy to ACR
    environment: dev
    env:
      image_name: tgc-regnerdetnu-api
      app_path: src/TGC.RegnerDetNu
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v6

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.REGNERDETNU_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.REGNERDETNU_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.REGNERDETNU_DEV_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name tgclzdevacr.azurecr.io

    - name: Build and publish webapi to ACR
      run: |
        docker buildx build . \
          --platform linux/arm64 \
          --tag $acr_registry/$image_name:${{ needs.tag_commit.outputs.version }} \
          --tag $acr_registry/$image_name:latest \
          --push
      working-directory: ${{ env.app_path }}

  build_web_api_amd_job:
    needs: [tag_commit]
    runs-on: ubuntu-latest
    name: Build Web API and deploy to ACR
    environment: dev
    env:
      image_name: tgc-regnerdetnu-api
      app_path: src/TGC.RegnerDetNu
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v6

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.REGNERDETNU_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.REGNERDETNU_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.REGNERDETNU_DEV_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name tgclzdevacr.azurecr.io

    - name: Build and publish webapi to ACR
      run: |
        docker buildx build . \
          --platform linux/amd64 \
          --tag $acr_registry/$image_name:${{ needs.tag_commit.outputs.version }} \
          --tag $acr_registry/$image_name:latest \
          --push
      working-directory: ${{ env.app_path }}

  build_deployment_files_dev_job:
    needs: [tag_commit, build_web_app_arm_job, build_web_app_amd_job, build_web_api_arm_job, build_web_api_amd_job]
    runs-on: ubuntu-latest
    name: Build deployment files DEV
    environment: dev

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Render manifests
      run: |
        helm template backend ./helm \
          -f ./helm/values-dev.yaml \
          --set api.image.tag=${{ needs.tag_commit.outputs.version }} \
          --set web.image.tag=${{ needs.tag_commit.outputs.version }} \
          --output-dir ./deployment/dev
    
    - name: Tag commit
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet || git commit -m "[TGC.AsgerThyregodDK] chore: render prd manifests [${{ steps.resolve_tag.outputs.IMAGE_TAG }}]"        
        git push
        git tag ${{ needs.tag_commit.outputs.version }}
        git push origin ${{ needs.tag_commit.outputs.version }}
  
  # build_deployment_files_prd_job:
  #   needs: [build_web_app_job, build_web_api_job]
  #   runs-on: ubuntu-latest
  #   name: Build deployment files PRD
  #   environment: prd

  #   steps:
  #   - uses: actions/checkout@v6

  #   - name: 'Az CLI login'
  #     uses: azure/login@v2
  #     with:
  #       client-id: ${{ secrets.REGNERDETNU_DEV_CLIENT_ID }}
  #       tenant-id: ${{ secrets.REGNERDETNU_DEV_TENANT_ID }}
  #       subscription-id: ${{ secrets.REGNERDETNU_DEV_SUBSCRIPTION_ID }}
  #       enable-AzPSSession: true

  #   - name: Resolve image tag
  #     id: resolve_tag
  #     uses: azure/powershell@v3
  #     with:
  #       azPSVersion: latest
  #       inlineScript: |
  #         ./scripts/fetch_latest_image_version.ps1 `
  #           -acrUrl "tgclzdevacr.azurecr.io" `
  #           -imageName "tgc-regnerdetnu-app" `
  #           -inputTag "${{ github.event.inputs.version || 'latest' }}"
    
  #   - name: Render manifests
  #     run: |
  #       helm template backend ./helm \
  #         -f ./helm/values-dev.yaml \
  #         --set image.tag=${{ steps.resolve_tag.outputs.IMAGE_TAG }} \
  #         --output-dir ./deployment/dev
  #     working-directory: asgerthyregoddk